"""followers

Revision ID: 20958ffcea0a
Revises: f61c368e5999
Create Date: 2018-12-17 00:40:01.759205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20958ffcea0a'
down_revision = 'f61c368e5999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
